### ISSUE TITLE
两个USB丢失问题，请问遇到过吗？

### ISSUE THREAD

**Issue by HemingwayZ** [kevinkochatt/ASRock-B460M-ITX-AC-Hackintosh#1]
![image](https://user-images.githubusercontent.com/15057998/130017167-2499d609-2616-49ea-b3e2-6fb63149d693.png)

好像是从bug sur 11.3.0开始出现的。
https://www.tonymacx86.com/threads/big-sur-11-3-update-broke-usb-3.312374/

尝试使用了您的efi，貌似也没有效果。
也有使用USBInjectAll

**Comment by HemingwayZ** [comment]
丢失USB3.0接口

**Comment by kevinkochatt** [comment]
Hmmm, thats really odd I don’t seem to have that issue, there was a point where my USB 3 refused to function at all like that bug described, but I wrote the exact steps to fix it in my case in the README of this build which I’m assuming you already saw and tried to recreate. (https://github.com/kevinkochatt/ASRock-B460M-ITX-AC-Hackintosh#fix-usb-30-and-port-mapping)

**Comment by kevinkochatt** [comment]
And just letting you know, once your USB ports are configured, you should NOT be using USBinjectAll, or your patch might not work properly, remember to Remove it! (But keep XHCIUnsupported)

**Comment by HemingwayZ** [comment]
Ok thanks
